# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    # I could not get the mongo db to work with the authentication for now. 
    # It will be some concern for another day.
    #environment:
    # MONGO_INITDB_ROOT_USERNAME: mongoroot
    # MONGO_INITDB_ROOT_PASSWORD: AVeryGoodPassword
    ports:
      - 27017:27017
    volumes:
      - ./.local-resources/db:/data/db
    #ports:
    # - 27017:27017

    # mongo-express:
    #   image: mongo-express
    #   restart: always
    #   ports:
    #     - 8081:8081
    #   environment:
    #     # ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #     # ME_CONFIG_MONGODB_ADMINPASSWORD: AVeryGoodPassword
    #     ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  backend:
    depends_on:
      - mongo
    build:
      context: ./plant-therapist-backend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
