# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    #environment:
    # MONGO_INITDB_ROOT_USERNAME: mongoroot
    # MONGO_INITDB_ROOT_PASSWORD: AVeryGoodPassword
    volumes:
      - C:\Data:/data/db
    #ports:
    # - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: AVeryGoodPassword
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  backend:
    depends_on:
      - mongo
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
