name: CI
on:
  push:
    branches: [ master ]
  
jobs:
  deploy:
    runs-on: self-hosted
    strategy:   
      matrix: 
        node-version: [18.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}

      - name: build docker image
        run: docker compose -f docker-compose.prod.yml build

      - name: run docker containers
        run: docker compose up -d

      #- run: npm install
      #- run: npm run build --if-present
      #- run: npm test