name: CI
on:
  push:
    branches: [ master ]
  
jobs:

  check-changes:
    runs-on: [self-hosted, linux]

    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}

    steps:
    - uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'plant-therapist-backend/**'
          frontend:
            - 'plant-therapist-frontend/**'

  build-and-deploy-backend:
    needs: check-changes
    if: ${{ needs.changes.outputs.backend == 'true' }}

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: build docker image
        run: docker compose -f docker-compose.prod.yml build

      - name: run docker containers
        run: docker compose up -d

  build-and-deploy-frontend: 
    needs: check-changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}

    runs-on: [self-hosted, linux]

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
            node-version: 18

      - name: install dependencies.
        run: npm install
        working-directory: plant-therapist-frontend

      - name: build the project
        run: npm run predeploy
        working-directory: plant-therapist-frontend

      - name: Upload pages artifacts
        uses: actions/upload-pages-artifact@v1
        with: 
          path: ./plant-therapist-frontend/build

      - name: Deploy to pages
        uses: actions/deploy-pages@v1
