name: CI
on:
  push:
    branches: [ master ]
  
jobs:
  build-and-deploy-backend:
    runs-on: self-hosted
        
    steps:
      - uses: actions/checkout@v3

      - name: build docker image
        run: docker compose -f docker-compose.prod.yml build

      - name: run docker containers
        run: docker compose up -d

  build-and-deploy-frontend: 
    runs-on: [self-hosted, linux]

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
            node-version: 18

      - name: install dependencies.
        run: npm install
        working-directory: plant-therapist-frontend

      - name: build the project
        run: npm run predeploy
        working-directory: plant-therapist-frontend

      - name: Upload pages artifacts
        uses: actions/upload-pages-artifact@v1
        with: 
          path: ./plant-therapist-frontend/build

      - name: Deploy to pages
        uses: actions/deploy-pages@v1